import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }: any) {
  console.log(data);
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <Link href="/">Home</Link>
          <Link href="/events">Events</Link>
          <Link href="/about-us">About Us</Link>
        </nav>
      </header>
      <main className={styles.main}>
        {data.map((ev: any) => (
          <Link key={ev.id} href={`/events/${ev.id}`}>
            <Image width={200} height={200} alt={ev.title} src={ev.image} />
            <h2>{ev.title}</h2> <p>{ev.description}</p>
          </Link>
        ))}
{/*         
        <Link href="/events/london">
          <h2>Events in London</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. A, fugit
            nisi! Tempore molestias omnis placeat iusto esse vitae, fuga nostrum
            est delectus doloribus, perferendis aliquam. Repudiandae aut ad
            facilis? Voluptatibus?
          </p>
        </Link>

        <Link href="/events/sanfran">
          <h2>Events in San Francisco</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. A, fugit
            nisi! Tempore molestias omnis placeat iusto esse vitae, fuga nostrum
            est delectus doloribus, perferendis aliquam. Repudiandae aut ad
            facilis? Voluptatibus?
          </p>
        </Link>

        <Link href="/events/london">
          <h2>Events in Barcelona</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. A, fugit
            nisi! Tempore molestias omnis placeat iusto esse vitae, fuga nostrum
            est delectus doloribus, perferendis aliquam. Repudiandae aut ad
            facilis? Voluptatibus?
          </p>
        </Link> */}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("../data/data.json");
  console.log(events_categories);

  return {
    props: {
      data: events_categories,
    },
  };
}
