import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About Us</a>
        </nav>
      </header>
      <main className={styles.main}>
        <a href="/events/london">
          <img />
          <h2>Events in London</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. A, fugit
            nisi! Tempore molestias omnis placeat iusto esse vitae, fuga nostrum
            est delectus doloribus, perferendis aliquam. Repudiandae aut ad
            facilis? Voluptatibus?
          </p>
        </a>

        <a href="/events/sanfran">
          <img />
          <h2>Events in San Francisco</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. A, fugit
            nisi! Tempore molestias omnis placeat iusto esse vitae, fuga nostrum
            est delectus doloribus, perferendis aliquam. Repudiandae aut ad
            facilis? Voluptatibus?
          </p>
        </a>

        <a href="/events/london">
          <img />
          <h2>Events in Barcelona</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. A, fugit
            nisi! Tempore molestias omnis placeat iusto esse vitae, fuga nostrum
            est delectus doloribus, perferendis aliquam. Repudiandae aut ad
            facilis? Voluptatibus?
          </p>
        </a>
      </main>
    </>
  );
}
